name: zotero-standalone
version: 0.1.0
summary: Zotero Standalone
description: |
  Zotero Standalone

grade: devel

confinement: strict

apps:
  zotero:
    command: desktop-launch $SNAP/zotero
    plugs:
      - x11
      - wayland
      - network-control
      - network-observe
      - firewall-control
      - home
      - gsettings
      - account-control
      - mount-observe
      - unity7
      - browser-support
      - desktop-legacy
      - desktop
      - network
      - process-control
      - system-observe

parts:
  zotero-standalone:
    plugin: dump
    source: https://www.zotero.org/download/client/dl?channel=release&platform=linux-x86_64
    source-type: tar
    stage-packages:
      - libxt6
    after:
      - desktop-gtk3

